services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: veb
      POSTGRES_PASSWORD: veb
      POSTGRES_DB: books
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - 9999:5432
volumes:
  pgdata:
